apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "eric-amos-odp-ssh-broker" "service" "name" }}-certreq-secret-1
  labels:
    serviceName: {{ index .Values "eric-amos-odp-ssh-broker" "service" "name" }}
    certRequest: "true"
type: Opaque
stringData:
  certReqName: "Amos_ssh_odp_broker_crem_CLI_cert_req.xml"
  certReqData: {{ .Files.Get "appconfig/certificatesdata/Amos_ssh_odp_broker_crem_CLI_cert_req.xml" | quote }}
# this field is not present at start-up (first installation):
# it is inserted during certs generation phase
#  certReqState:
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "eric-amos-odp-ssh-broker" "service" "name" }}-tls-secret-1
  labels:
    certReqName: "{{ index .Values "eric-amos-odp-ssh-broker" "service" "name" }}-certreq-secret-1"
type: Opaque
# these fields are not present at start-up (first installation):
# they are inserted during certs generation phase
#stringData:
#  tlsStoreLocation:
#  tlsStoreType:
#data:
#  tlsStoreData:
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "eric-amos-odp-ssh-broker" "service" "name" }}-tls-secret-2
  labels:
    certReqName: "{{ index .Values "eric-amos-odp-ssh-broker" "service" "name" }}-certreq-secret-1"
type: Opaque
# these fields are not present at start-up (first installation):
# they are inserted during certs generation phase
#stringData:
#  tlsStoreLocation:
#  tlsStoreType:
#data:
#  tlsStoreData:
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "eric-amos-odp-ssh-broker" "service" "name" }}-tls-secret-3
  labels:
    certReqName: "{{ index .Values "eric-amos-odp-ssh-broker" "service" "name" }}-certreq-secret-1"
type: Opaque
# these fields are not present at start-up (first installation):
# they are inserted during certs generation phase
#stringData:
#  tlsStoreLocation:
#  tlsStoreType:
#data:
#  tlsStoreData:
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ index .Values "eric-amos-odp-ssh-broker" "service" "name" }}-tls-secret-4
  labels:
    certReqName: "{{ index .Values "eric-amos-odp-ssh-broker" "service" "name" }}-certreq-secret-1"
type: Opaque
